### ISSUE TITLE
Issue with docker context - Permission denied on /var/run/docker.sock

### ISSUE THREAD

**Issue by ddetommaso** [s4hri/dockyman#2]
If docker context is configured differently than default we get this error on building dockyman images:

DOCKYMAN -> Building BASE image iitschri/null-docker:v0.0.1 ...
Param: image_name: 'iitschri/null-docker:v0.0.1'
Param: workspace_folder: './base/image'
Param: push: 'false'
[5 ms] @devcontainers/cli 0.64.0. Node.js v20.4.0. linux 6.8.0-35-generic x64.
[2034 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.64.0-1718723289598/Dockerfile-with-features -t iitschri/null-docker:v0.0.1 --target dev_containers_target_stage --build-arg DOCKER_SRC=alpine:latest --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /shared/base/image
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://api.moby.localhost/_ping": dial unix /var/run/docker.sock: connect: permission denied
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.64.0-1718723289598/Dockerfile-with-features -t iitschri/null-docker:v0.0.1 --target dev_containers_target_stage --build-arg DOCKER_SRC=alpine:latest --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /shared/base/image
    at mtA (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1933)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Pm (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:1856)
    at async FrA (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:661:24467)
    at async yrA (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:661:22292)
{"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.64.0-1718723289598/Dockerfile-with-features -t iitschri/null-docker:v0.0.1 --target dev_containers_target_stage --build-arg DOCKER_SRC=alpine:latest --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /shared/base/image","description":"An error occurred building the image."}
make: *** [Makefile:300: build-base] Error 1

**Comment by ddetommaso** [comment]
To check context run:

`docker context show`

using default context, will fix the issue:

`docker context use default`
